server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml       # mybatis 配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities  #  所有 Entity 别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper 映射文件

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver            #  mysql 驱动包
    url: jdbc:mysql://118.31.58.177:3306/microservice?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                            # 数据库连接池的最小维持连接数
      initial-size: 5                                        # 初始化连接数
      max-total: 5                                           #  最大连接数
      max-wait-millis: 200                                  #  等待连接获取的最大超时时间
